export const OBTER_PROJETO = "OBTER_PROJETO"
export const CADASTRAR_PROJETO = "CADASTRAR_PROJETO"
export const ALTERAR_PROJETO = "ALTERAR_PROJETO"
export const REMOVER_PROJETO = "REMOVER_PROJETO"

export const OBTER_TAREFA = "OBTER_TAREFA"
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA"
export const ALTERAR_TAREFA = "ALTERAR_TAREFA"