export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETOS"
export const ALTERAR_PROJETOS = "ALTERAR_PROJETOS"
export const REMOVER_PROJETOS = "REMOVER_PROJETOS"